- crafting_pieces.xml
- items.json
- items/weapons.xml
(FIX) Edited the following items:
- crpg_empire_noble_sword_1_t5 | Decorated Short Spatha
- crpg_empire_noble_sword_2_t5 | Thamaskene Steel Spatha
- crpg_empire_noble_sword_3_t5 | Spatha Blade with Ring Pommel
- crpg_empire_sword_2_t3 | Spatha With Narrow Fuller
- crpg_empire_sword_3_t3 | Spatha
- crpg_empire_sword_4_t4 | Fine Steel Spatha
- crpg_empire_sword_5_t4 | Fine Steel Paramerion
- crpg_empire_sword_6_t5 | Thamaskene Steel Spathion
- crpg_iron_spatha_sword_t2 | Iron Spatha
Find additional details [here](https://docs.google.com/spreadsheets/d/1sTt6PEGD3EHn-EBzABQRszbdwDkoSAa765WSm8Vb5JE/edit#gid=1341011737) (Empire Changes).
> 1h sword empire edits

- crafting_pieces.xml
- items.json
- items/weapons.xml
these polearms have been adjusted and I attempted the length change on the Warrazor and Polesword:
Fine Steel Menav
Rhomp
Polesword
Billhook
Practice Spear
Warrazor
> some swing polearms done

- crafting_pieces.xml
- items.json
- items/weapons.xml
> Reworked Heavy Executioner Axe into Long Bladed Bardiche Tier 10

- items.json
- items/weapons.xml
Reworked 4 bows to the Charger Bow archetype
Made Charger Bows within each tier groups: 10-8-6-5
Made Charger Bows focused around Accuracy and Aim Speed
increased accuracy for lower tier to increase accessibility for lower level of investment
> Charger bow rework

- crafting_pieces.xml
- items.json
- items/weapons.xml
updated all battania 1h swords
> Total rebalance of all battania 1h swords

- crafting_pieces.xml
- items.json
- items/weapons.xml
Updated changes to the following items based on feedback (higher tier) clean-up:
Morningstar
Spiked Mace
Highland Spiked Club
Spiked Club
> 1h spiked mace edits

- crafting_pieces.xml
- items.json
- items/weapons.xml
(FIX) Edited the following items. Fixed stab values based on feedback:
- crpg_aserai_noble_sword_1_t5 | Decorated Kaskara
- crpg_aserai_noble_sword_2_t5 | Decorated Long Scimitar
- crpg_aserai_noble_sword_3_t5 | Decorated Scimitar with Wide Grip
- crpg_aserai_noble_sword_4_t5 | Engraved Angular Kaskara
- crpg_aserai_sword_1_t2 | Iron Flyssa
- crpg_aserai_sword_2_t2 | Iron Scimitar
- crpg_aserai_sword_3_t3 | Slightly Ridged Flyssa
- crpg_aserai_sword_4_t4 | Fine Steel Long Kaskara
- crpg_aserai_sword_5_t4 | Long Fine Steel Scimitar
- crpg_aserai_sword_6_t4 | Narrow Fine Steel Kaskara
- crpg_aserai_sword_7_t5 | Thamaskene Steel Kaskara
Find additional details [here](https://docs.google.com/spreadsheets/d/1sTt6PEGD3EHn-EBzABQRszbdwDkoSAa765WSm8Vb5JE/edit#gid=1341011737) (Aserai Changes).
> 1h sword aserai edits

- crafting_pieces.xml
- items.json
- items/weapons.xml
- Glaive
- Long Glaive
- Voulge
- Menavlion
- Scythe
> Glaive, L.Glaive, Voulge, Menavlion, Scythe

- crafting_pieces.xml
- items.json
for some reason the 1h and 2h damage is identical, im not sure if the game will reflect those numbers.
> ridged great saber rework 4

- crafting_pieces.xml
- items.json
Based on new tier update from length impact, updated the following weapons:
- Long Glaive
- Menavlion
- Scythe
> Updated L.Glaive, Menav, Scythe

- items.json
- items/weapons.xml
Slight increase to heavy xbow damage, with light xbows getting accuracy, missile speed buffs (will be adjusted later to factor in use xbow cav), longer reload speed and slight increase to aim speed across the board, new high tier light xbow (Squire's light crossbow)
> Overall xbow buff plus new Squire's Light xbow

- crafting_pieces.xml
- items.json
- items/weapons.xml
All 3 weapons remain practically the same with slight adjustments to bring them to tier 10 and be competitively viable for the 2h apocalypse
> 2h Axes Top Tiers for new tier weights

- crafting_pieces.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
t10 thru t7, 1.0.0.4 tier calcs, rebase not screwed up this time. wep description changes are either removing or adding 1h modes
ridged great sabre having .1 damage is on purpose, lokiphur wanted to work on it but i had already changed it so i just made it low dmg until he can submit.
> Abearirl2hv3

- crafting_pieces.xml
- items.json
- items/weapons.xml
Brought the Simple raider axe up in tier and took off the "simple" from the name. Also upgraded the large Franziska axe and Broad Tzikourion
> +dmg +length +speed

- items.json
- items/weapons.xml
Hopefully i did this right, its from the new exporter.
> Hopefully doing this right - AP Bolts

- crafting_pieces.xml
- items.json
- items/weapons.xml
Long Bardiche Added
_Renaming "Long Bladed Bardiche" to "Large Bladed Bardiche" to avoid confusion with new Tier 7.2 "Long Bardiche"_
Northlander Decorated Axe tuned
Bearded Axe tuned
> Filling out 2h Axe 7-8 Tiers

- items.json
- items/shields.xml
- items/weapons.xml
Making small shield high tier for future cav to use
> Highest armor shield

- items.json
- items/weapons.xml
I tried to make these bows usable by those who dont invest heavily into bow proficiency, for those who like to focus an melee as well. I raised the nordic out of irrelevance and made it the antithesis to the noble (short) bow.
> 2 Yews Ranger Nordic Bow Rework

- crafting_pieces.xml
- items.json
- items/weapons.xml
Black Heart,
Drilled Two Handed Axe, 
Hooked Cavalry Axe to Hooked Axe, 
Short Bill, 
Square Bit Two Handed Axe, 
Simple Sparth Axe, 
Hoe 
New T9 Weapon "Chainbreaker" a more 1v1 focused Bardiche similar to Northlander Broad Axe
> 2h axe t1-7 + Short Handled Bardiche to t9 weapon "Chainbreaker"

- crafting_pieces.xml
- items.json
- items/weapons.xml
Mid-Tier (7) 2h rework: Long Kaskara (aim for long), Highland 2h (aim for fast), Highland fine 2h (aim for damage)
> Mid Tier 2h rework

- crafting_pieces.xml
- items.json
- items/weapons.xml
Third try on low tier(5) 2h rework.
> Change Low Tier 2h

- crafting_pieces.xml
- items.json
- items/weapons.xml
Updated the following due to Exporter v1.0.0.6:
- Glaive
- L.ong Glaive
- Voulge
- Menav
- Scythe
> Updated Glaive, L.Glaive, Voulge, Menav, Scythe

- crafting_pieces.xml
- items.json
- items/weapons.xml
Reworked the following items based on new tiers:
- crpg_empire_noble_sword_1_t5 | Decorated Short Spatha
- crpg_empire_noble_sword_2_t5 | Thamaskene Steel Spatha
- crpg_empire_noble_sword_3_t5 | Spatha Blade with Ring Pommel
- crpg_empire_sword_2_t3 | Spatha With Narrow Fuller
- crpg_empire_sword_3_t3 | Spatha
- crpg_empire_sword_4_t4 | Fine Steel Spatha
- crpg_empire_sword_5_t4 | Fine Steel Paramerion
- crpg_empire_sword_6_t5 | Thamaskene Steel Spathion
- crpg_iron_spatha_sword_t2 | Iron Spatha
Find additional details [here](https://docs.google.com/spreadsheets/d/1sTt6PEGD3EHn-EBzABQRszbdwDkoSAa765WSm8Vb5JE/edit#gid=1341011737) (Empire Changes).
> 1h empire edits rework

- crafting_pieces.xml
- items.json
- items/weapons.xml
Rework to the following items based on new tiers:
- Morningstar
- Spiked Mace
- Highland Spiked Club
- Spiked Club
> 1h spiked mace rework

- crafting_pieces.xml
- items.json
- items/weapons.xml
Reworked the following items. Fixed values based on new tiers:
- crpg_aserai_noble_sword_1_t5 | Decorated Kaskara
- crpg_aserai_noble_sword_2_t5 | Decorated Long Scimitar
- crpg_aserai_noble_sword_3_t5 | Decorated Scimitar with Wide Grip
- crpg_aserai_noble_sword_4_t5 | Engraved Angular Kaskara
- crpg_aserai_sword_1_t2 | Iron Flyssa
- crpg_aserai_sword_2_t2 | Iron Scimitar
- crpg_aserai_sword_3_t3 | Slightly Ridged Flyssa
- crpg_aserai_sword_4_t4 | Fine Steel Long Kaskara
- crpg_aserai_sword_5_t4 | Long Fine Steel Scimitar
- crpg_aserai_sword_6_t4 | Narrow Fine Steel Kaskara
- crpg_aserai_sword_7_t5 | Thamaskene Steel Kaskara
Find additional details [here](https://docs.google.com/spreadsheets/d/1sTt6PEGD3EHn-EBzABQRszbdwDkoSAa765WSm8Vb5JE/edit#gid=1341011737) (Aserai Changes).
> 1h sword aserai edits rework

- crafting_pieces.xml
- items.json
Edits to:
- Slightly Ridged Flyssa
- Ridged Saber
> 1h sword aserai edits 

- crafting_pieces.xml
- items.json
- items/weapons.xml
Rework to the following items based on feedback:
- Morningstar
- Highland Mace (now called Light Morningstar)
> 1h spiked mace edits new

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/horses_and_others.xml
- items/weapons.xml
- weapon_descriptions.xml
Updated Menavlion, Glaive, Voulge, Long Glaive.
Created modifiable Bo Staff.
> LUBU Polearms V5

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
1 pike touched up : Pike increased length to 500 adjusted weight, tiering a bit weird, same for 2d spears, tiering works fine for 4d spears
> 4d,2d,fork readjustment,pikes left out

- crafting_pieces.xml
- items.json
- items/weapons.xml
Changes to the following items:
- Thamaskene Steel Spatha
- Spatha with Narrow Fuller
- Fine Steel Spatha
> 1hswordsempire

- crafting_pieces.xml
- items.json
- items/weapons.xml
Changes to the following items: 
- Decorated Scimitar with Wide Grip
- Fine Steel Long Kaskara
> 1hswordaseraifinal

- crafting_pieces.xml
- items.json
Final balancing on the following items:
- Highland Spiked Club
- Spiked Club
> 11.22 - Spiked Mace Final

- crafting_pieces.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
updated for 1.0.0.5 and fixed/included lokiphur's ridged sabre changes
> Abearirlv4

- items.json
- items/weapons.xml
Adjusting Names and Squire's reload speed. (It was too fast)
> Xbow changes

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
Created Heavy Morningstar (2h version of morningstar).
> 2hmorningstar - Heavy Morningstar

- items.json
- items/weapons.xml
Normalizing xbow bolt weights. (Make heavier)
> Normalizing xbow bolt weights. (Make heavier)

- crafting_pieces.xml
- items.json
- items/weapons.xml
I brought the Large franz and raider battle axe into line with the new axe tier fix.
> Rebalnced 2 axes to work in tiers

- crafting_pieces.xml
- items.json
- items/weapons.xml
Simple Bastard Sword was missed during the initial edits.
renamed to Simple Warsword and culture changed from Neutral to Sturgia
> Simple Warsword

- crafting_pieces.xml
- items.json
All weapons readjusted with some feedback from tests and readjusted from the latest exporter
> 1h swords update: Battania Khuzait Vlandia Neutral

- crafting_pieces.xml
- items.json
- items/weapons.xml
Brought up some maces that were under t6 and maces balanced before the 50% change.
> Brought some low maces up tiers

- crafting_pieces.xml
- items.json
- items/weapons.xml
Updated 12 Lances and Glaive. Specifically selected 3 lances to become 250 length (1h), 265 length (1h), 285 length (2h only).
> Lubu poles v7

- items.json
- items/weapons.xml
Added the "Strong Tribal Long Bow" to give pure longbowmen another option beside the Noble Long Bow. Added 1 damage, and 3 middile speed, with a decrease in accuracy, aim speed, and a small decrease in reload. Still under Noble in tier but comparable, and will satiate some archers wants for more damage. Just a little more.
> Strong Tribal Long Bow Add

- items.json
- items/weapons.xml
Trying to make cut arrows a little more viable
> buffing cut arrows

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
Added two new 2hers based on the 1h variant.
> 2hadditions - Decorated Great Saber & Great Thamaskene Steel Spatha

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
Created the Blacksmith Warhammer. Will need to test the pieces and look before going to live.
> 1hhammer - (testing) Blacksmith Warhammer

- crafting_pieces.xml
- items.json
- items/weapons.xml
Added knockdown to the hammer.
> 1hhammer - Knockdown

- crafting_pieces.xml
- items.json
Nerfed morningstar damages based on community feedback.
> Morningstar reworks - Damage Nerf

- items.json
- items/weapons.xml
As requested 3 top tier bows with no auto reload. I simply copied the bottom 3 bows for ease of access, yew is not top tier but has low reload, so will provide a wider array of "data". I apologize for the delay, didnt notice the comment for a few days.
> Experimental Manual Noble Long+Short+Yew

- crafting_pieces.xml
- items.json
bringing broad kaskara up to t10
> broad kaskara - t10 38cut 87sp

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
Reworked a few of the Sturgia swords based on speed/damage.
> 1hswordsturgia - Rework

- fakeclanandusersforbannerbalancing.cs
generated fake players for team balance tests
> Generatedusers

- items/horses_and_others.xml
Currently players can't mount horses because they don't meet the skill requirements. Not sure what has changed but setting the difficulty to all horses to 0 fixes it.
> Set all mount difficulty to 0

- crafting_pieces.xml
- items.json
- items/weapons.xml
slight changes to dmg & speed on around half or less of axes
> 1hAxe Balancing pass, slightly increased dmg and shortened

- crafting_pieces.xml
- items.json
Nerf 4 two hand-swords that had above 100 swing speed, Wooden 2h, Iron Broadsword, Highland Broadsword, Ridged Great Saber
> 4 2hand-swords nerf down speed

- items.json
- items/weapons.xml
> 1h axe name changes

- crafting_pieces.xml
- items.json
reverting an accidental change that got through somehow on the sturgia rework
> 1H Swords Simple Scimitar Fix

- crafting_pieces.xml
- items.json
- items/weapons.xml
fixed fine pike
also realized i had to fix thamaskene, so i ended up doing that too
> pike grip fix

- crafting_pieces.xml
- items.json
- items/weapons.xml
Vlandia rework to emphasize a thrust focus. all swords at least 20 thrust
one battania sword also adjusted to differentiate it from the vlandia changes, fit with battania's hard hitting theme.
> 1H Swords Vlandia Rework

- crafting_pieces.xml
- items.json
problem is the tier drop from 8/9 down to tier 4 or 5 while still being pretty good
> nerfed polearm swing speed on some 4d polearms

- crafting_pieces.xml
- items.json
- items/weapons.xml
> 12.12 - Blacksmith Warhammer Rework

- crafting_pieces.xml
- items.json
Adjusted damage between 1h/2h morningstars to be slightly closer.
> Morningstarrework - Slight Damage Adjustment

- crafting_pieces.xml
- items.json
- items/weapons.xml
Reworked the following weapons over tier:
- Decorated Scimitar with Wide Grip
- Decorated Elite Scimitar
- Thamaskene Steel Spatha
- Thamaskene Steel Spathion
- Engraved Angular Kaskara
> 1h tier rework - Aserai/Empire

- crafting_pieces.xml
- items.json
- items/weapons.xml
first part of the spear revision after budget adjustment - forks
> spear revision 1, forks

- items.json
- items/weapons.xml
Tweaked one light xbow and added another. 12/15 STRG Reqs.
> Light xbow changes

- crafting_pieces.xml
- items.json
- items/weapons.xml
Applying exporter v12 has caused the tier of most items to change very slightly.
> Slightly nerfed Sturgia 1h Swords to below t10

- crafting_pieces.xml
- items.json
Battania, Khuzait, Vlandia and Neutral 1H Swords updated for new exporter and mod update
> v12 Exporter Update for AngryMob 1H Swords

- crafting_pieces.xml
- items.json
- items/weapons.xml
Modified the following items:
- Modified the Thamaskene Steel Kaskara (1h) to have more stab damage
Reworked Naming conventions/scaling for the following:
- Decorated Great Saber
- Great Thamaskene Steel Claymore
> 12.19 - Decorated Great Saber & Thamaskene Steel Claymore 2h scaling/rework, 1h Kaskara

- crafting_pieces.xml
- items.json
- items/weapons.xml
Modified the following items: 
- Steel Mace
- Knight's Fall
- Fullered Western Mace
- Judgement
- Bonecrusher
- Light Royal Mace
- Pernach
> 12.29 - 1H Maces

- crafting_pieces.xml
- items.json
Blacksmith Warhammer:
- Modified damage for slightly more speed.
> 12.29 - Blacksmith Warhammer

- items.json
- items/horses_and_others.xml
Refunds the latest renamed mounts and trophy mounts.
> HORSEREFUNDS MOUNTv2

- crafting_pieces.xml
- items.json
- items/weapons.xml
balance changes after handling budget update
> 1h axe.handling update.jan2023

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
fixed decimels
Longsword (sentinel)
length 105->107
thrust dmg 14->17
swing dmg 35-> 40
swing spd 94 -> 96
+onehand mode
+side scabbard
Thamaskene (muhloord)
Renamed back to Thamaskene by popular request
length 122 -> 127
thrust dmg 18 -> 22
swing spd 85 -> 91 
+side scabbard
harvesting season
speed 76-> 81
barmace 
dmg 30 -> 28
speed 82 -> 88
wide fullered
length 131 -> 135
thrust dmg 12 -> 19
swing dmg 34 -> 39
speed 90 -> 87
falx 
length 135 -> 130
speed 80 -> 89 
claymore
speed 85 -> 81
northlander
swing dmg 37 -> 38
speed 92 -> 91
dawn
swing dmg 31->38
speed 78 -> 84
heavy executioner
swing dmg 44 -> 45
swing speed 77 -> 78
winter
thrust dmg 20 -> 21
> v14 sentinel+thamaskene

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
EDIT: Created the Soldier's Cleaver.
> 1.17 - Soldier's Cleaver

- crafting_pieces.xml
- items.json
- items/weapons.xml
> 1/19 - 1H Maces

- items.json
- items/arm_armors.xml
- items/body_armors.xml
- items/head_armors.xml
- items/leg_armors.xml
- items/shoulder_armors.xml
Changing all Aserai Armors' value
> ALLAseraiArmorsChange

- items.json
- items/arm_armors.xml
- items/body_armors.xml
- items/head_armors.xml
- items/leg_armors.xml
- items/shoulder_armors.xml
> ALLVlandiaArmorsChange

- crafting_pieces.xml
- crafting_templates.xml
- items/body_armors.xml
- items/head_armors.xml
- items/shields.xml
- items/shoulder_armors.xml
- items/weapons.xml
- weapon_descriptions.xml
Added items:
by ADamnSexyName: 2x Western Sallet, 2x Western open Sallet, 2x Vaegir Coat of Plates, Vaegir Noble Helmet, Vaegir Helmet, 2x Vaegir Helmet, War Mask, War helmet, Roundtop Full Helm, Round Top Great Helmet
by Blink: Roningasa
by Skye: Simple Poleaxe, Burgundian Poleaxe, Burgundian Glaive, French Voulge
by gp: Bec De Corbin, Spiked Polehammer, Warhammer, Military Hammer, Heavy Goedendag, Medium Goedendag, Light Goedendag
by meow: 6x Katana, 1x Oval Buckler
Added crpg_SideTwoHandedSword in crafting_templates for side holstered 2h swords.
Buckler collision changes and stats tweak - need to be checked by the shield crew.
Barbute facial hair fixed.
Reintroduced Reinforced Leather Armor
Reintroduced Round Buckler
> Meow custom items - Rebase

- crafting_pieces.xml
- items.json
- items/weapons.xml
PR for edits to:
* Military Hammer
* Warhammer
* Medium Goedendag
* Light Goedendag
> 1h maces - custom

- items.json
- items/arm_armors.xml
- items/body_armors.xml
- items/head_armors.xml
- items/leg_armors.xml
- items/shoulder_armors.xml
All Head, Body, Shoulder, Arm, and Leg armors for Khuzait and Neutral cultures revamped armor values according to the new system
> Armor Revamp - Khuzait Neutral - AngryMob

- items.json
- items/horses_and_others.xml
Basically a -6HP pre-emptive nerf based on recent feedback.
> Mount Rebalancing v1.2 -> v1.2b

- items.json
- items/body_armors.xml
- items/shoulder_armors.xml
fixed a few typos in the armor values found using the items spreadsheet.
> Armor Revamp - Typo Fixes

- items.json
- items/horses_and_others.xml
Sumpter 194 to 195 HP
Brabant 235 to 225 HP
Apologies, my mistake - I just double checked through them now, had to head out this morning shortly after submitting last PR, didn't get the chance.
> v1.2b (small typo fix, HP, Sumpter and Brabant Greathorse)

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
2d spears reworked and voulge rename
> Spear revision part 2

- crafting_pieces.xml
- items.json
- items/weapons.xml
- weapon_descriptions.xml
almost done :D removed redundant spears (2 of them) , fit spears into better defined roles
> Spear revision part 3

- items.json
- items/horses_and_others.xml
Désolé, yet another pre-patch minor adjustment. 
Also updated cultures.
> Mounts v1.2 - Greathorse -1 SPD upper tiers (minor adjustment)

- items.json
- items/horses_and_others.xml
as title says. no rush, nothing game-breaking. 2 HP difference.
> Mounts v1.2b - HP adjust (Kehilan al-Khamsa mount) 209 to 207

- crafting_pieces.xml
- items.json
candismount changes from 4d > 2d spears and adresses its inconsistencies
> remake of previous pr

- crafting_pieces.xml
- items.json
- items/weapons.xml
addresses several things:
too similar weapons without distinguishing qualities
lack of affordable good slashing poles (most are high tier, or really really long if around 5-8)
> Simple pole axe and french voulge

- items.json
- items/head_armors.xml
Takeo's Crown
Takeo's Fleur De Lis
> Added Takeo's Gear

- items.json
- items/shields.xml
changed holster to lower back position to prevent melee collision issues when in hand. redid collisions so bucklers don't float.
This PR requires the new pack file.
> Fixed buckler issues - merge after #232 Minor shield updates.jan2023

- crafting_pieces.xml
- items.json
- items/weapons.xml
Modified the below based upon feedback from the community. Also took some damage off of the Pernach to keep it in-tier.
> 2.20 - 1h tweaks

- crafting_pieces.xml
- crafting_templates.xml
- items.json
- weapon_descriptions.xml
> minor 2h tweaks

- crafting_pieces.xml
- items.json
Noble Cav Lance (Remove CanDismount) crpg_khuzait_lance_3_t5_guard
> Noble Cav Lance (Remove CanDismount) crpg_khuzait_lance_3_t5_guard

- items.json
- items/weapons.xml
reverting change to dawnbreaker to fix tier: length 99 -> 102
> 1hSwords - Dawnbreaker Fix

- crafting_pieces.xml
- items.json
Modified the below. Most were over T10 from recent updates. Took knockdown off of the Military Hammer to make it viable.
> 2.27 - 1h changes

- items/banners.xml
- items/body_armors.xml
- items/horses_and_others.xml
- items/shoulder_armors.xml
- mesh/prefab changed for banners which caused crashes
- dresses have a gender variation now
- some appearance changed, not sure what it does
- remove horse flags
> Align item attributes with native

- items/banners.xml
I forgot to add the crpg_ prefix
> Fix banner ids

- items.json
- items/body_armors.xml
- items/head_armors.xml
- items/shoulder_armors.xml
also added noglow takeo crown
changed tabbard to tabard on the existing ones.
> Added Mail with Tabard Heraldic

- items/shields.xml
> Changed buckler weapon_class to a working one.

- crafting_pieces.xml
- items.json
- items/weapons.xml
https://docs.google.com/spreadsheets/d/1J6MDB6O9nDqUdmGNP2OPXnqSyeuTvYnUa5cxBfDc_3U/edit?usp=sharing
See: Polearms Comparison sheet for items stats.
Slight improvements to lance rework, minor changes.
> Lance Rework 1 (Adjustment, improved upon slightly)

- items/shields.xml
The SmallShield weapon class was tested on ~40 shields and I didn't find any problem.
> Separate large/small shields

- items.json
- weapon_descriptions.xml
For some reason, the spears weren't in the pike category. I don't understand how this reversed as I was sure I went through them thoroughly. I'm suffering withdrawal atm from antidepressants so mind is frazzled, this is adding to the confusion greatly. Hey ho, onwards and upwards. I have addressed this in PR.
Also, I am working on the theory that bracing and couching x function has disappeared all the two-hand lances from the shop, so I have adjusted the required weapon descriptions.
> Fixes following lance rework 1

- crafting_pieces.xml
- items.json
- items/weapons.xml
- lowered spear damage and added can dismount
- swapped can dismount from Jereed to horseman
- lowered/varied a few redundant jav damages to create better spread
- changed broadblade to cut damage for more choice/variation
> Javelin.may2023update

- crafting_pieces.xml
- items.json
- items/weapons.xml
This should make them much more appealing in current meta without making them completely broken.
> Lance Update (removing some redundancy in structure and +1 pierce buff overall)

- crafting_pieces.xml
- items.json
Updated the following spears, loosely following the pattern below:-
+1 (+1 speed)
+2 (+1 damage)
+3 (+1 speed)
Simple pike
Iron Pitchfork 
Pitchfork 
Wide Leaf Spear
Fine Steel Hewing Spear
Fine Pike
Hoplite Spear
> Heirloom spears

- crafting_pieces.xml
- items.json
https://docs.google.com/spreadsheets/d/1G-nn5KeMVP84JMxMeu3wP8vUn3bEZKsYW65K6l3ha-E/edit?usp=sharing
Loom scheme and tier changes ^
> 1h axe heirlooms

- crafting_pieces.xml
- items.json
https://docs.google.com/spreadsheets/d/1G-nn5KeMVP84JMxMeu3wP8vUn3bEZKsYW65K6l3ha-E/edit?usp=sharing
Loom scheme and tier changes ^
> 1h dagger heirlooms

- crafting_pieces.xml
- items.json
https://docs.google.com/spreadsheets/d/1G-nn5KeMVP84JMxMeu3wP8vUn3bEZKsYW65K6l3ha-E/edit?usp=sharing
ADJUSTED (flagged swords that are changed with this tag on the sheet^)
> 1h heirlooms (redressing top tier)

- crafting_pieces.xml
- items.json
reduced stats for some SwingPolearms, provide details stats below (note, each stat will be compared to original stats that is in the live server atm)
> 6.27SwingPolearmChanges

- crafting_pieces.xml
- items.json
+3 given +1 speed, had one less by mistake.
> Heavy Knightly Lance Heirloom Fix

- items.json
- items/weapons.xml
Fixing an error made by myself (committing changes directly to items.json instead of weapons.xml 
Reverted mistake made in items.json back to how it was before
Made changes in weapons.xml to set all items to v2 to give new names to all
> Fix mistake by myself made to Hoplite Spear

- crafting_pieces.xml
- items.json
Crafted stats for the Rondel Dagger from +0 to +3
> Crafted Item - Rondel Dagger

- crafting_pieces.xml
- items.json
- items/weapons.xml
Meow updated the model. I made it unsheathable and updated heirloom dmg
> Pilum mesh replacement

- items/head_armors.xml
these were checked and adjusted by Swagathor
> Updated hair and beard cover types for head gear

- crafting_pieces.xml
- items.json
Reworked Broad Shortsword to be more like it was in cRPG 1
> Broadshortsword Rework making it like in cRPG 1

- items.json
- items/weapons.xml
Corrected Loomed Names (Added +1/+2/+3)
> Broad Short Sword

- items/shields.xml
since we found the issue with the shield collisions the buckler can go back to the hip.
> Moved buckler back to the hip holster

- crafting_pieces.xml
- items.json
- items/weapons.xml
v1.0 of Wakizashi and Tanto Stats
**h0**
length **65**
handling **90**
swingSPD **93**
swingDMG **33**
**h1**
swingDMG **34**
**h2**
swingDMG **36**
**h3**
swingDMG **37**
**h0**
length **65**
handling **90**
swingSPD **93**
swingDMG **32**
**h1**
swingDMG **33**
**h2**
swingDMG **35**
**h3**
swingDMG **36**
**h0**
length **65**
handling **90**
swingSPD **93**
swingDMG **31**
**h1**
swingDMG **32**
**h2**
swingDMG **34**
**h3**
swingDMG **35**
**h0**
length **50**
handling **106**
swingSPD **97**
swingDMG **29**
thrustSPD **85**
thrustDMG **31**
**h1**
handling **107**
swingSPD **99**
thrustSPD **87**
thrustDMG **32**
**h2**
handling **108**
swingSPD **100**
thrustDMG **33**
**h3**
swingSPD **100**
swingDMG **30**
thrustDMG **34**
> Yeldur WakizashiTanto v1.0

- items.json
- items/body_armors.xml
Assigned Body armours,
Bahamut plate - comparing it to others, very well rounded coverage, new highest weight body, especially as a non-EBA armour, it has decent leg, Still only 61 body though.
Western cuirass was assigned wrong mesh- double check I named mesh correct (there is striped and non-striped cuirass)
> Final Batch of body armours assigned

- items.json
- items/weapons.xml
fixed naming issue, no stats change
> fixed naming issue when heirloomed for a few weapons

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- Removed scabbard from nodachis
- Adjusted wakizashi scabbard colors to fit the handle
- Fixed dagger scabbard template
- Moved meowdao to backholster
> Various Item Fixes:

- crafting_pieces.xml
- items.json
Fixes an issue with the barmace in which the stab exclusion item_usage_feature was accidentally left out.
> 1h barmace stab fix

- crafting_pieces.xml
- crafting_templates.xml
- items/arm_armors.xml
- items/body_armors.xml
- items/head_armors.xml
- items/leg_armors.xml
- items/shields.xml
- items/shoulder_armors.xml
- items/weapons.xml
- weapon_descriptions.xml
> Meows spooky item batch

- items.json
- items/body_armors.xml
Changed Tabard over Coat of Plate Stripes and it's 2 variants - names were mixed up for pattern
> Changed name to match patterns

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
lightweight, good reach, fast but lower dmg
heirlooms levels all add +1 dmg
> Bamboo spear

- crafting_pieces.xml
- items/weapons.xml
Kriegsmesser-Rework:
- Fullscale=True enabled for better look
- Rebalanced: Slighty shortened, increased damage to make it a slashing-type sword
- Refunded
> Reworked Kriegsmesser

- items/horses_and_others.xml
This removes the harnesses for horses that players clip into since they are single player items for pack mules etc.
> Initial Commit removing the packs and load harnesses for horses.

- crafting_pieces.xml
- items/weapons.xml
item.json shows many changes, only the crpg_heavy_morningstar_v1 h0-h3 changed in this branch
> Morningstar Replacement - Initial Commit with new stats and refund

- items/weapons.xml
- Fixed Missing H1 of Piercing Arrows
> Fixing Missing H1 of Piercing Arrows

- crafting_pieces.xml
- items/weapons.xml
Rebalanced the Burgundian Poleaxe following requests to elongate it
Changed length to 150
Lowered stats at each loom tier to ensure it did not go overbudget
Refunded item
> YeldurBurgPolev2

- crafting_pieces.xml
- items/weapons.xml
Updates Iron Rod to T7, this is to fit in line with some polearm structure changes being put underway at present
> Yeldur iron rodv2

- items/head_armors.xml
- items/weapons.xml
> Meow helmets 1

- crafting_pieces.xml
- items/weapons.xml
•	Updated 1h Axe Heirlooms to be more damage focused
•	Lowered speed on Long Tzikourion Axe to add more damage
•	Added ‘Light’ prefix on Tzikourion Axe
•	Renamed Wood Splitter to Head Splitter
•	Refunded any axe changed
> 1h axe.heirloom update.dec2023

- items/body_armors.xml
Western Cuirass had striped version for the meshes of each loomed version
> Norr: WesternCuirass correct loom model

- items/horses_and_others.xml
Adding mount types to 'trophy mounts' in order to ease accessibility / understanding of the list.
> Adding Mount Types to Trophy Mount Names

- crafting_pieces.xml
- items/weapons.xml
German Halberd given BvS and slight damage reduction to stay within tier
Fine Steel Paramerion handle resized down, blade length increased to account for lost reach and weights adjusted
Affected weapons refunded
> German Halberd BvS & Fine Steel Parameion handle

- items/head_armors.xml
- items/shields.xml
- items/weapons.xml
Xmas refunded and disabled
Axe thing diggles will sort out in here
> disable xmas items

- items/weapons.xml
Corrected mistake of not incrementing the version for the Steel Footman Axe in last update
> corrected version number on base item

- items/weapons.xml
Set fixed price as an exception to not require exporter changes at the moment.
Added weight.
> Smokebomb - price and weight increase

- crafting_pieces.xml
Retiered swing polearms to mostly where they were before, re-doing as I don't actually know how to rebase and keep breaking items.
> Retier swing polearms

- items/weapons.xml
post damage nerf and tier changes
> refund-2h-poles

- items/weapons.xml
Changed blunt to pierce for all arrows and refunded.
> Changed blunt arrows to pierce and refunded

- items/weapons.xml
Refunded all xbows and bolts for STR change, pending: https://github.com/namidaka/crpg/pull/339
> Refunded all xbows and bolts for STR change

- crafting_templates.xml
- item_usage_sets.xml
- items/weapons.xml
- weapon_descriptions.xml
Second attempt at adding polearm 2D mode for swing over head and thrust only. 
Applied 2D moveset (swing overhead, stab thrust and no side swings) to Swiss Halberd and English Bill for live testing,
> 2D polearm swing/thrust

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
> Initial Commit Small Hammer

- crafting_pieces.xml
- items/weapons.xml
xbow req
small hammer and horseman's fix
> Xbow items fix

- items/body_armors.xml
Added Lorica Musculata by GulagEnabler sponsored by Yeldur
> Added Lorica Musculata

- items/weapons.xml
Refunding German Halberd ( was missed on PR review from #493 )
> Refunding German Halberd

- items/body_armors.xml
- items/head_armors.xml
- items/leg_armors.xml
- items/shoulder_armors.xml
- weapon_descriptions.xml
Add Sutton Armor sponsored by Argoth, copied locally to own branch as exporter wasn't working on Meows PR.
> Sutton Armour - Offline version so my exporter works

- items/weapons.xml
Added +1/2/3 to Horseman's Axe naming as it was missing (stats weren't affected)
> Added +1/2/3 to Horseman's Axe naming

- crafting_pieces.xml
Rebalanced Candy Cane weapons to not be so fast and overbearing. Stayed around the same Tier where possible.
> Rebalanced Candy Cane Weapons

- items/shoulder_armors.xml
Adds fluted pauldrons and gorget, negates PR#498
> Add Fluted Pauldrons and Gorget

- items/head_armors.xml
Add 4 FLuted CLose Helms negates PR#499
> Add Fluted Helmets 

- items/shields.xml
Changed physics_material of steel heater shield to "metal_shield" so it makes the correct sounds on block.
> Fix physics_material of steel heater shield

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
- Ancient Fighting Axe. Corrected primary mode for shop/cost/inventory loom to 1h. Changed alt mode from 2haxe to 2hsword.
- Zweihander. Corrected primary mode for shop/cost/inventory loom to polearm.
- Long Bardiche. Renamed to Great Long Bardiche. New Long Bardiche created.
> Salt dec2024 fixes tweaks

- items/head_armors.xml
Added Helmet sponsored by Kume
> Added Kume Helmet

- action_sets.xml
- action_types.xml
- collision_infos.xml
- items/weapons.xml
- physics_materials.xml
The new files are already on the crpg repo, these are copies of them with handgonne requirements added.
> Meow handgonne

- items/head_armors.xml
add appletruce and Meow collab Morion
> Add Morion Helmet

- items/body_armors.xml
Fix split brig with cuises entries to point to correct mesh, thank you rfl fdor pointing out this error
> Corerct mesh name

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
- Adjusted Zweihander polearm mode to use up allowed budget (previously was well below)
- Added polearm alt mode for Claymore
> Polearm alt modes - Adjusted Zwei and added Claymore

- crafting_pieces.xml
- items/weapons.xml
First take on where we should sit the Handgonne stat wise. Current thoughts:
- High end of damage, but not new highest
- Highest missile speed
- "Poor" accuracy (same as Fine Light Crossbow) to make sniping with the missile speed not as appealing
- Slow reload speed
- Slow aim speed
- Heavy to stop kiting rats
- STR req (and therefore Tier) at 21 - taking ammo into consideration, it is about as powerful as the Knights Heavy + best bolts (within 1 damage) and less damage than the 2 Lords xbows
> Handgonne stats and musket type and cartridge

- items/head_armors.xml
Correct the spelling & grammar used in 'bacinet with facemask'
'bacinet with facemask' -> 'Bascinet with Facemask'
> Correct grammar/spelling of helmet

- crafting_pieces.xml
- items/shields.xml
To replace https://github.com/namidaka/itembalancing/pull/550 as I messed that one up (sorry Meow)
also includes whitespace fix for templar sword
> Orle Shield & whitespace fix for templar sword

- items/head_armors.xml
Added Helmet from https://www.nexusmods.com/mountandblade2bannerlord/mods/2325
Ref:
https://github.com/namidaka/itembalancing/pull/552
> Add Bear Helmet

- items/shields.xml
Add large heater shield
Address issues with smaller heater shield (currently marked as too long which will make item lighter)
> Added large heater

- items/head_armors.xml
Recreated from https://github.com/namidaka/itembalancing/pull/558
Rebasing was running into issues that made conflict worse, as a result opted to spend less time on issue by re-creating PR.
> Morion Armour Reduction

- items/arm_armors.xml
- items/leg_armors.xml
- items/shoulder_armors.xml
v2 Add Maj Ham native Bannerlord kitbash armor, leg, arms and shoulders.  Replaces PR 551.
> v2 Add Maj Ham armor

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
- Redistributed weights on English Bill to avoid unintended weapon behaviour
- Added polearm Great Long Maul
- Added javelin War Darts
> New weapons and tweaks

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
Test melee alt modes for Tribesman Throwing Axe & Pilum. Specific stats rather than autocalc through BL. 
Tribesman Axe Melee mode ~T3.0
Pilum melee mode ~T1.0
> Test alt modes for Tribesman Throwing Axe + Pilum

- items/body_armors.xml
- items/shields.xml
Adding 1 body armor pieces and 1 shield by Scorilo prepared and imported by Maj.Ham
> Add aciv body & Aciv shield

- items/shields.xml
Adjusted size and rotation on the Parma Shields
Change Sutton Shield from hand_shield to shield
> Changed Parma and Sutton Shield

- items/leg_armors.xml
Added 6 leg armor pieces by Scorilo prepared and imported by Maj.Ham
> Added leg armor pieces from aciv

- items/shoulder_armors.xml
Added 7 shoulder armor pieces by Scorilo prepared and imported by Maj.Ham
> Added shoulder armors from aciv

- items/shields.xml
The size change was applied but the rotation was not adjusted accordingly. This has been fixed now.
> Changed rotation on parma shields

- crafting_pieces.xml
- items/weapons.xml
reduce swing speed increase damage remove can Dismount
> reduce swing speed increase damage remove can Dismount

- items/weapons.xml
> Added Yumi

- items/body_armors.xml
Added 15 body armor pieces by Scorilo prepared and imported by Maj.Ham
> Added aciv body armors

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
> New weapons

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
Added Broken Sword by Bob, textures by meow, stats by Yeldur
> Added Bob's Broken Sword

- crafting_pieces.xml
- crafting_templates.xml
- weapon_descriptions.xml
items.json push, can be merged directly without review
> items.json push

- items/head_armors.xml
Corrected pricing for Painted Chalcidian Helm and Bronze Chalcidian Helm (they were set manually)
> Removed manaul values from 2 head armours

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
> Added Nagamaki

- crafting_pieces.xml
This fixes some blanks in crafting_pieces.xml so it won't show up on every autocalc on new branches.
> Autocalc and export of current main

- collision_infos.xml
Forgot to add the hit effect for firearms (long time ago), this enables them again.
> Added firearm effects

- items/shields.xml
> Added brass variant of the Vergina Sun Shield

- items/horses_and_others.xml
Cavalry refund to go with: https://github.com/crpg2/crpg/pull/563
> Refund cavalry for cavalry breaker changes

- items/head_armors.xml
Identical stats to Spiked Helmet with Facemask.
> Added Spiked Helmet with Waspmask

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
> Added Dadao

- items/body_armors.xml
reduce landsknecht cuirass leg armor and add loom calculations to assassains armor added by meow
> reduce landsknecht cuirass leg armor

- crafting_pieces.xml
- crafting_templates.xml
- items/weapons.xml
- weapon_descriptions.xml
> Added Kopis

- crafting_pieces.xml
- items/weapons.xml
Reduced thrust damage to 32p and then swing damage on looms to match new tier.
> Pompeian Gladius Nerf
