items.json
items/weapons.xml

This is one of the 5 archetypes rebalance for bows (Yumi Bows)
- Enabled 3 longbows on horses
- Rebalanced those bows between tiers category: 10-8-6
- Bows are designed to make lower tier accessible with lower wpf

New Yumi bow Archetype

---

items.json
items/weapons.xml

Reworked 4 bows to the Medium Bow archetype
>Made Medium Bows within each tier groups: 10-8-6-5
>Made Medium Bows focused around being the most balanced playstyle
>increased accuracy for lower tier to increase accessibility for lower level of investment

Medium bow rework

---

items.json
items/weapons.xml

Reworked 4 bows to the longbow archetype
>Made longbows within each tier groups: 10-8-6-5
>Made longbows focused around Damage and projectile speed
>increased accuracy for lower tier to increase accessibility for lower level of investment

Long bow rework

---

items.json
items/weapons.xml

Reworked 4 bows to the Short Bow archetype
>Made Short Bows within each tier groups: 10-8-6-5
>Made Short Bows focused around Reload Speed and Aim Speed
>increased accuracy for lower tier to increase accessibility for lower level of investment

Short bow rework

---

crafting_pieces.xml
items.json
items/weapons.xml
weapon_descriptions.xml

Balanced the following weapons:
- Glaive
- Long Glaive
- Voulge (BonusAgainstShield included in Tier)
- Menavlion
- Scythe
One concern I had, was that adding the BonusAgainstShield flag to Voulge also seems to apply to its 1h mode. Is there a way to do this without its 1h mode including the flag?

Item Balancing: 5 Swinging Polearms

---

crafting_pieces.xml
items.json
items/weapons.xml

4 different 1h for playtesting and checking limits of new formula
Decorated Broadsword = tier 10 slow but 37 cut damage
Engraved Backsword = tier 10 balanced stats
Broad Ridged Shortsword = tier 8.5 very short and quick
Fine Steel Cavalry Broadsword = tier 8.5 very long test

1h Swords for testing

---

items.json
items/weapons.xml

Rebalanced all charger bow to have at least 80 missile speed by slowing down reload speed.
Having them below that threshold made projectiles too hard to predict when shooting from a moving horse.

Missile speed rebalance (charger bows)

---

items.json
items/weapons.xml

Removed the bonus against shield modifier, broad head arrows went from 4 to 10 damage, light bha went from 2 to 6 damage, and from 22 to 33 stack.

broad head arrows cut damage

---

crafting_pieces.xml
items.json
items/weapons.xml

initial stats pass on all khuzait 1h swords
Tall Gripped Ild Sword - renamed to Tall Gripped Ild to remove redundant word
Decorated Saber - renamed to Decorated Cavalry Saber to indicate cavalry specialty
Lion Imprinted Saber
Fine Steel Saber
Long Saber - renamed to Fine Steel Cavalry Saber to indicate specialty and fit with lineup
Straight Saber
Heavy Saber
Broad Ild
Iron Saber
Simple Saber
Simple Scimitar

1h swords khuzait initial stats pass

---

crafting_pieces.xml
items.json
items/weapons.xml

Initial pass on stats for all neutral culture 1h swords:
Winds Fury - changed to a cavalry sword so that neutral has one and so one of the unique tournament trophy swords is one
Scalpel - cutting trophy sword
Tyrhung - thrusting trophy sword
Dawnbreaker - balanced trophy sword
Star Falchion
Pointed Falchion
Broad Falchion
Falchion - renamed to Iron Falchion to fit lineups better
Cleaver - renamed to Iron Cleaver to fit lineups
Wooden Sword
 
Following swords arent included in this patch because they will be changed to other cultures in those cultures' respective patches:
Broad Arming Sword - moving to Vlandia
Short Sword - moving to Vlandia
Narrow Sword - Moving to Sturgia
Simple Bastard Sword - Moving to Sturgia

1h Swords Neutral initial stats pass

---

crafting_pieces.xml
items.json
items/weapons.xml

All battania 1h swords given a thorough rebalance with new tier formula
Engraved Backsword
Decorated Broadsword
Highland Broad Blade
Broad Ridged Shortsword renamed to Fine Steel Broad Shortsword to fit in the lineup of broadswords better
Highland Fine Steel Blade renamed to Highland Highland Pointed Blade to indicate thrust specialty
Fine Steel Cavalry Broadsword
Broadsword renamed to Steel Broadsword to fit in the lineup of broadswords better
Ridged Iron Broadsword

1h Swords Battania update to new tiers

---

crafting_pieces.xml
items.json
items/weapons.xml

Initial stats pass on all Vlandia 1h swords and 2 additional swords from neutral
extensive renaming as well to reduce wordiness and repetition of "arming sword" somewhat and make the specializations more clear
Decorated Arming Sword
Gold Engraved Arming Sword - renamed to Engraved Pointed Sword
Knightly Arming Sword - renamed to Knightly Cavalry Sword
Arming Sword with Circle - renamed to Fine Steel Arming sword
Wide Fullered Broad Arming Sword - renamed to Fine Steel Cavalry Sword
Ridged Arming Sword - renamed to Narrow Arming Sword
Short Sword - changed culture from Neutral, renamed to Short Arming Sword
Crescent Guarded Arming Sword - renamed to Crescent Arming Sword
Broad Arming Sword - changed culture from Neutral, renamed to Iron Pointed Sword
Ridged Tipped Arming Sword - renamed to …

1h swords vlandia

---

crafting_pieces.xml
items.json
items/weapons.xml

Tier update for all previously balanced 1h swords from battania, khuzait, and neutral cultures.
also swapped the names:
Pointed Falchion - renamed to Broad Falchion because it cannot thrust
Broad Falchion - Renamed to Pointed Falchion because it can thrust

1h Swords Tier Update

---

crafting_pieces.xml
items.json

Didn't quite get them where I wanted, but this seems decent enough.
| Name | Tier | Length | Cut | Stab | Cut spd | Stab spd |
|-|-|-|-|-|-|-|
| Decorated Fullered Sword | 10.5 | 102 | 35 | 12 | 82 | 87 |
| Decorated Long Warsword | 10.1 | 111 | 34 | 17 | 81 | 86 |
| Gold Bound Short Warsword | 10.0 | 84 | 28 | 18 | 91 | 87 |
| Thamaskene Steel Warsword | 8.6 | 104 | 33 | 16 | 83 | 87 |
| Long Warsword | 8.1 | 100 | 28 | 12 | 88 | 87 |
| Fullered Narrow Warsword | 7.6 | 86 | 27 | 16 | 93 | 89 |
| Backsword | 7.2 | 90 | 28 | 11 | 88 | 89 |
| Fullered Long Warsword | 6.4 | 98 | 31 | 15 | 86 | 87 |
| Pointy Warsword | 6.1 | 92 | 24 | 15 | 92 | 91 |
| Tapered Blade | 5.5 | 89 | 27 | 13 | 90 | 87 |
A few things I learned about the tier calculator:
* Values a light blade very strongly. Adding …

1h sword sturgia

---

items.json
items/weapons.xml

Reeling the squire's xbow in just a bit, decreased it's accuracy from 98 to 97, increased it's reload to 55 from 52, originally was at 58. Huntsman's Heavy Crossbow renamed to Heavy Hunting Crossbow, Lord's Heavy Arbalest (Bound) weight adjusted from 5.2 to 5.5 to standardize the weight value of it with the other xbows. Gave the rest of the heavy xbows the affix "CanPenetrateShield" which didn't have it previously.

Squire xbow reload buff hunstman xbow name change

---

crafting_pieces.xml
items.json
items/weapons.xml

most changes to address the speed/length limits and update the tiers. most weapons are near the limit because khuzait is sorta my polar opposite of battania stats wise. intended to be fast.
-Tall Gripped Ild - nerfed overall. slower, shorter, less swing damage. given better thrust to compensate
-Broad Ild - same damage, 1 point faster than tall gripped, but even shorter and no good thrust
Decorated Cavalry Saber - the only 1h cavalry sword to be 78 speed pending approval. easily can walk this back if its too much. lowered swing damage to compensate
Lion Imprinted Saber - shorter and slower to fit within the rule, more damage to compensate
Fine Steel Saber - slightly faster than lion imprinted, but weaker and shorter
Iron Saber - straight downgrade of lion imprinted, may rethink this one …

1H Swords Khuzait Rework

---

crafting_pieces.xml
items.json
items/weapons.xml

Mostly just tweaks needed for battania:
-brought tiers back to desired values
-raised the main broadsword speeds to 80 instead of 78
-left the decorated broadshort a bit shorter and 79 speed to hopefully make the mid tiers more appealing, not just flat-out worse options. thanks gp for making me think about this better
-increased damage on pointed and shortsword, trying to solidify battania as the hard hitting culture at expense of speed

1H Swords Battania Rework

---

crafting_pieces.xml
items.json
items/weapons.xml

several adjustments for the length/speed limits. otherwise just brought tiers back to desired spots and tweaked to find niche stats for each sword
Winds Fury - no longer a cav sword. name was confusing people since the name sounds fast, but cav swords are slow...
Wooden Sword - technically breaks the speed limit, but its the wood sword so guessing its fair?

1H Swords Neutral Rework

---

crafting_pieces.xml
items.json
items/weapons.xml

Additionally, stab buffs to align with other factions
- Fullered Long Warsword: speed-, damage+, stab+
- Pointy Warsword: length+, speed-, damage+
- Long Warsword: speed-, damage+, stab+
- Decorated Long Warsword: speed+
- Thamaskene Steel Warsword: speed+, damage-
- Tapered Blade: stab+
- Backsword: stab+
- Fullered Narrow Warsword: stab+, damage-

Fix Sturgia 1h swords speed/length limits

---

crafting_pieces.xml
items.json
items/weapons.xml

Following weapons affected:
Glaive (89 speed -> 84 speed, thrust is now cut)
Long Glaive
Menavlion
Voulge
Billhook
War Scythe
Rhomphaia
Bo Staff (18b swing -> 14b, 18b thrust -> 10b)
Long Bardiche
Long Hafted Spiked Mace

Adjusted swing poles according to V12

---

items.json
items/horses_and_others.xml

Don't have to approve anytime soon or at all. Could some beta testing be done though?
Added Rouncey and Great Horse archetype. Relevelled and rescaled the tiers and archetypes - plateaus at the higher tiers (if this seems like too little of a difference and/or too many mounts, a regular scale can be put back in which would provide more tier 5 mounts, or the split-tier can be removed altogether to reduce overall amount):
https://docs.google.com/spreadsheets/d/1luwvL72ImLhD-NW47wwFmCOLjAwMrR6LUka5cydIHnI/edit?usp=sharing
Archetypes explained etc on sheet. Also added in a comparison to main for stats, with the Rouncey compared to Balanced mounts, and the Great Horse compared to Charger mounts. Left in Sargonid and Seleucid camels unintentionally, but they fill in the gaps of the tier …

Mount Rework v1.1

---

items.json
items/arm_armors.xml
items/body_armors.xml
items/head_armors.xml
items/shoulder_armors.xml

Missing native armors added, and some existing armors renamed to fit with the new additions:
Helmets:
crpg_southern_lord_helmet - Ornate Desert Helmet
no renames
Bodies:
crpg_khuzait_leather_stitched - Stitched Cured Leather Vest
crpg_sturgian_lamellar_gambeson - Heavy Lamellar Vest
existing Heavy Lamellar Vest renamed to Heavy Lamellar Vest with Skirt and stats changed to cavalry type to reflect skirt
Shoulders:
crpg_noble_pauldron_with_scarf - Ornate Pauldrons over mail
crpg_desert_scale_shoulders - Long Sleeved Steel Scale Shoulder Guards
crpg_a_aserai_scale_b_shoulder_e - Long Sleeved Bronze Scale Shoulder Guards
existing Long Sleeved Bronze Scale Shoulder Guards renamed to Long Sleeved Decorated Scale Shoulder Guards
Arms:
crpg_lordly_padded_mitten - Decorated Padded Mittens …

Armor Revamp - Missing Armors - AngryMob

---

crafting_pieces.xml
items.json
items/weapons.xml

Complete rework of all Sturgian 1H swords. refund included for all swords. The "handling focus" was an unsuccessful subclass. The new focus is on various shortswords, with 1 group of normal swords as well,
new groups and names as follows:
"Choppers"
Decorated Long Warsword		 ---> Decorated Long Warsword
Fullered Long Warsword			 ---> Steel Long Warsword
Long Warsword				 ---> Iron Long Warsword
"Short Balanced"
Thegn Sword					 ---> Engraved Thegn Blade
Tapered Blade					 ---> Iron Thegn Blade
"Short Choppers"
Gold Bound Short Warsword		 ---> Gold Bound Short Warsword
Thamaskene Steel Warsword		 ---> Thamaskene Short Warsword
Simple Warsword				 ---> Simple Short Warsword
"Short Slashers"
Decorated Fullered Sword		 ---> Decorated Northern Backsword
Backsword					 ---> Northern Backsword …

1H Swords - Sturgia Rework - AngryMob

---

crafting_pieces.xml
items.json
items/arm_armors.xml
items/body_armors.xml
items/head_armors.xml
items/leg_armors.xml
items/shoulder_armors.xml
items/weapons.xml

Rework a few polearm and entered first stats for 6 new polearms.
Long Bardiche:
swing damage 49 --> 48
swing speed 76 --> 75
thrust damage 23 --> 24
Weight 1.65 --> 1.7
Reach 161 --> 158
handling 67 --> 65
Voulge:
swing damage 47 --> 44
swing speed 82 --> 81
thrust damage 21 --> 22
Weight 1.45 --> 1.47
Menavlion:
swing damage 38 --> 41
swing speed 83 --> 80
thrust damage 23 --> 22
Weight 1.72 --> 1.84
handling 72 --> 69
Long Glaive:
swing speed 76 --> 73
thrust damage 24 --> 25
thrust speed 96 --> 95
Weight 1.35 --> 1.44
handling 65 --> 63
Billhook:
swing damage 48 --> 45
Glaive:
swing speed 84 --> 83
thrust speed 95 --> 94
Weight 1.63 --> 1.68
handling 72 --> 71
Long Hafted Spiked Mace:
swing damage 27 --> 25
thrust damage 16 --> 17
Weight 1.83 --> 1.87
Reach 154 --> 155
War Scythe: …

Polearm change

---

crafting_pieces.xml
items.json

PR theme video: https://www.youtube.com/watch?v=wAkCLpMtjlM
will keith roleplay mode unlocked (katanas balanced) 
goedendag balanced
all 2h weps above t10 brought down (maces) 
crushthrough weps may need additional nerfs in the future (imo)
also - all the new stuff needs thumbnails still i think, but i dont have the meshes locally (i think??) so exporting creates black squares

Hanzo steel and goedendag

---

items.json
items/horses_and_others.xml

As before, small maneuver structure change. This xml is functional, however. 
Removed part of the split tier for maneuver (two tiers sharing same value) towards the top, as it seemed slightly redundant/excessive. It has actually led to nice options comparatively amidst the lowest tiers. The structure seems to make more sense overall as well.
Apologies for committing another PR before first one even made it to patch - however imo it would make more sense to release it with these changes than to worry about applying these changes after a patch, once people have repurchased mounts, etc.
Easy to compare document showing all mounts:
https://docs.google.com/spreadsheets/d/1luwvL72ImLhD-NW47wwFmCOLjAwMrR6LUka5cydIHnI/edit?usp=sharing
Also, see Champion Mounts.

Mount Rebalancing v1.2

---

crafting_pieces.xml
items.json
items/weapons.xml

Buffed some mid-tier 2h swords and a low tier 2h.
Tapered two-hander 
swing damage: 20 ->34
swing speed: 81 ->78
thrust damage: 12 ->16
thrust speed: 90 ->89
reach: 133 ->145
handling: 84 ->78
Iron Broadsword
swing damage: 24 ->25
swing speed: 97 ->97
thrust damage: 9 ->10
thrust speed: 94 ->94
reach: 104 ->104
handling: 89 ->89
Highland Broadsword
swing damage: 27 ->28
swing speed: 80 ->97
thrust damage: 12 ->14
thrust speed: 88 ->94
reach: 113 ->113
handling: 84 ->89
Ridged Great Saber
swing damage: 28 ->29
swing speed: 98 ->97
thrust damage: 13 ->14
thrust speed: 94 ->94
reach: 118 ->114
handling: 89 ->88
Justicier
swing damage: 26 ->32
swing speed: 90 ->86
thrust damage: 11 ->14
thrust speed: 92 ->97
reach: 117 ->127
handling: 85 ->83

ReworkMidTier2hSwords

---

crafting_pieces.xml
items.json
items/weapons.xml

Follow with the newest thrust patch fix
Bec De Corbin
Thrust damage 25–>23
Billhook
Weight 1.91–>1.95
Handling 69–>68
Swing damage 45–>46
Swing speed 82–>81
Burgundian Glaive
Thrust damage 22–>21
Swing damage 44–>45
Burgundian Poleaxe
Weight 2.27–>2.33
Handling 72–>71
Swing damage 42–>43
Swing speed 82–>81
BvS flag added
Polesword
Swing damage 47–>48
Menavlion
Thrust damage 22–>23
French Voulge
Weight 1.99–>2.15
Handling 75–>72
Thrust damage 23–>24
Thrust speed 93–>92
Swing damage 37–>41
Swing speed 88–>84
Glaive
Weight 1.68–>1.71
Handling 71–>70
Thrust damage 25–>24
Swing damage 41–>43
Swing speed 83–>82
Long Bardiche
Weight 1.7–>1.73
Length 158–>161
Thrust damage 24–>26
Swing damage 48–>49
Swing speed 75–>74
Long Hafted Spiked Mace
Weight 1.87–>1.91
Handling 67–>66
Thrust speed 93–>92 …

Polearms changes update

---

items/horses_and_others.xml

Although I did check this way back using the mesh viewer tool, I didn't anticipate it would be this close to black. 
White has dappling/grey tones which would be much more suitable for Marengo.

Marengo (simple Grey to White)

---

crafting_pieces.xml
items.json
items/weapons.xml

Updated all battania, khuzait, sturgia, vlandia, and neutral 1h swords:
-exporter version 21
-large thrust damage increases where possible - especially on thrust specialty swords. others try to get around 20 minimum for viability. traded a bit of other stats to accomplish where required.
-fixed tiers that were off from planned tiers - including the last minute >t10 adjustments from last patch
-substantial nerfs due to tier adjustments were given refunds:
crpg_sturgia_noble_sword_1_t5_v2
crpg_khuzait_sword_4_t4
crpg_bastard_sword_t2_v2
crpg_sturgia_sword_1_t2_v2
-substantial rebalance to make these more unique were given refunds:
crpg_tyrhung_sword_t3
crpg_dawnbreaker_sword_t3

1H Swords - AngryMob

---

crafting_templates.xml
items.json
items/weapons.xml
weapon_descriptions.xml

Added a weapon_description crpg_ThrowingHammer that sets the throwing weapons in it to not get stuck in the target.
Also included crpg_Mace and crpg_ThrowingHammer in the crpg_ThrowingAxe crafting_template.
This way throwing blunt weapons and pieces can be put into the crpg_ThrowingAxe crafting_template and then into the crpg_Mace and crpg_ThrowingHammer weapon_description to get the correct flags.
This was already done for the Throwing Maul.

Throwingmaul tweaks

---

crafting_pieces.xml
items.json

3 polearms change:
Bec De Corbin
- new tier: 9.65598 
- thrust damage from 27 to 26
Tall Tipped War Spear
- new tier: 9.944908
- swing speed from 71 to 70
- weight from 1.4 to 1.46
- handling from 59 to 58
Long Thamaskene Tipped Spear
- new tier: 9.736737
- swing speed from 70 to 68
- thrust speed from 91 to 90
- weight from 2.03 to 2.07
- handling from 59 to 58

PolearmChanges

---

crafting_pieces.xml
items.json
items/weapons.xml

Since axes suffer from sweet spots, lowered length on most to make it less likely to get bad swing. Increased damage to make them more dangerous and destroy shields better.  Moved 2 ugly axes (Squarebit and Northlander Broad) that noone uses to lower tiers in order to bump up some other ones.

2 haxe.may2023.update

---

crafting_pieces.xml
items.json

A list with changes to tier, showing the increase/decrease at h3 from h0,  as well as the stat changes per heirloom level. Some I've flagged to see if I can get it closer to **1.0** tier difference i.e. **+/- 0.2**, such as **0.7** or **1.3**:
https://docs.google.com/spreadsheets/d/1G-nn5KeMVP84JMxMeu3wP8vUn3bEZKsYW65K6l3ha-E/edit?usp=sharing
Flagged swords are in bold - either due to their tier difference or due to the amount of damage points added (i.e. 5 Thrust and 2 Swing - Gold Bound Short Warsword, 3 Thrust and 3 Swing - Wooden Sword, 3 Thrust and 2 Swing - Spathas, etc) which I perhaps couldn't balance with just increases to speed & swing damage.

1h sword & mace heirlooms

---

crafting_pieces.xml
items.json

Resolve a typo created when making the +2 heirloom state of the Hoe (intended to be 2.8 to fall in line with loom elevation per level but mistyped as 3.8)

Fixing a typo in the +2 loom state of the Hoe

---

crafting_pieces.xml
items.json

short leaf spear - given increased stats at +3
+3 stats created
hoplite spear - rebalanced item heirloom tiers to be a bit more consistent
+1 buffed
+2 buffed
+3 nerfed (ID changed to push refund for +3 tier only)

Rebalance for Hoplite Spear/Short Leaf Spear

---

crafting_pieces.xml

Adding heirloom stats for Hooked Javelins 
Rebalancing Jagged Javelins (dmg increase to 32) - requested by diggles
Adding heirloom stats for Jagged Javelins and balanced them around new tier changes made by damage increase
Rebalancing Horseman Javelins (+1 to ammo, dmg reduction to 26, weight to 1.5) - requested by diggles
Rebalanced Horseman Javelins heirloom stats to fit changes made to base weapon.

Rebalance & add loom stats to throwing items

---

crafting_pieces.xml
items.json
items/weapons.xml

The main objective of the four-directional polearm adjustment is to modify the panel attribute data of individual polearms that are of normal length (around 140) and some that are excessively long (over 170). This adjustment aims to reduce the swing damage while providing compensation in terms of swing speed (some received thrust damage and speed adjustments as well). All weapons will have some differences in their adjusted tiers, but the differences will not be significant. If these weapons do not receive a slight power level decrease in game after this update goes live, there will be a budget allocated for a minor decrease in the 4d polearm. All adjusted weapons have been refunded.
Billhook h0
- swing damage from 46 to 44 
- swing speed from 79 to 80
- weight from 2.05 to 2.01 
- …

7.10 swingpolarm adjustments

---

crafting_pieces.xml
items.json
items/weapons.xml

Reworked daggers from ground up following a pattern like so regarding tier:
**Rondel#⁠1-Stab 8.0**
_Seax#⁠1-Cut 6.5_ 
**Pugio#2-Stab 6.5**
_Xiphos#2-Cut 4.5_
**Falx#3-Stab 4.5**
_Highland#3-Cut 3.0_
The aim is to have 2 daggers at **high tier stab and cut**, 2 daggers at **mid-tier stab and cut**, 2 daggers at **low-tier stab and cut**
Given the deficits of stab, it has a higher tier compared to cut, as cut has less restrictions applied and more freedom as a weapon.

Yeldur-Dagger Rework

---

crafting_pieces.xml
items.json
items/weapons.xml

Revamp of the Katana's, offering unique tiers for each one 
- Shortened length of all to 95 from 102 (Feels more logical to push them further into a shorter region)
- Set tier for Green and Red to be focused around 9.0 (stats slightly increased due to lower length)
- Set tier for Blue and Yellow to be focused around 7.5 (stats slightly decreased due to lower length but lower tier)
- Set tier for Black to be focused around 6.5 (stats slightly increased due to lower tier)
- Changed weapons.xml to force a refund to all Katana tiers
- Set all Daggers to host my name alongside them given that I am managing daggers from a crafting perspective (commented like kaikaikai's against polearms)

Yeldur Katana Rework

---

crafting_pieces.xml
items.json
items/weapons.xml

Heavy Goedendag is one of our professionally designed weapons from gp - I believe in its current state it is underutilised because it has the Knockdown stat, which renders its stats incredibly low - Overall it doesn't gain any real benefit from knockdown at the stage it's at because of how low the damage is. 
This change does the following:
- Removed Knockdown from HGD
- Increased thrust/swing damage to compensate
- Tried to tiermatch as much as possible but did increase tier marginally. 
- Changed ID to push a refund of this item given the fundamental change in how it performs
**+0**
- Thrust damage 2.8 -> 3.2
- Swing damage 2.4 -> 2.9
**+1**
- TD 2.8  -> 3.3
- SD 2.4 -> 3.0
- weight 1.0 -> 1.1
**+2**
- TD 2.8 -> 3.3
- SD 2.5 -> 3.1
- wgt 1.1 -> 1.05
**+3** 
- TD 2.8 -> 3.3
- SD 2.6 -> …

Rework of Heavy Goedendag

---

items.json
items/weapons.xml

Updates Polearms to have better naming conventions that are either more comfortable or more logical.
Early Halberd -> **Voulge**
Done because the Voulge is the commonly known name for this weapon, the change was, although historically accurate because this isn't actually a Voulge, unnecessary and confusing. (Sorry historybros)
Short Raider Spear -> **Vanguard's Short Spear**
Highland War Spear -> **Highland Marshal's Spear**
Simple Commoner Spear -> **Noble Hunting Spear**

Polearm Renaming

---

crafting_pieces.xml
items.json
items/weapons.xml

###Rondel Dagger###
Added 4 length to the Rondel (41 -> 45) 
###Shepherd's Axe###
- Added length to Shepherd Axe (88 -> 95)
- Increased damage (2.5 -> 3.6)
- Lowered speed (95 -> 84)
- Weight increased (0.97 -> 1.11)
- Name changed to Shepherd's Axe
- Refund issued due to rebalance changing the core of how this weapon functions

Rebalance to Rondel & Shepherd's Axe

---

crafting_templates.xml
items.json
items/weapons.xml
weapon_descriptions.xml

Originally intended to fix errors with the wakizashi and tanto this turned into a collection of fixed through the xml files to make sure all items in our item xml files are actually in the items.json.
fixed items are:
crpg_narrow_sword_h0 - h3 the pommel piece was missing in the weapons_descriptions.xml but not in the crafting_templates.xml
crpg_common_hunting_bow_h0 - h3  was missing the crpg_ tag in front of the id and was not considered by the exporter
katana, tanto and wakizashi were setup wrong by me and the weapon_descriptions were missing the crpg_ tag.

Wakizashi nodachi

---

crafting_pieces.xml
items.json
items/weapons.xml

stats input for a 1h sword: Jian
specific stats for the weapon:
Jian h0
swing damage 35
swing speed 82
thrust damage 19
thrust speed 91
tier 9.97
weight 1.44
length 109
handling 83
Jian h1
swing damage 35
swing speed 83
thrust damage 22
thrust speed 91
tier 9.40
weight 1.42
length 109
handling 83
Jian h2
swing damage 37
swing speed 83
thrust damage 22
thrust speed 91
tier 9.92
weight 1.42
length 109
handling 83
Jian h3
swing damage 37
swing speed 84
thrust damage 23
thrust speed 92
tier 9.76
weight 1.37
length 109
handling 84

NewOneHandedSword stats input

---

crafting_pieces.xml
items.json
items/weapons.xml

stats input for three new 2h swords: Meowdao, Zweihander, Executioner's Sword
specific stats for each weapon:
Meowdao h0
-   swing damage 43
-   swing speed 80
-   thrust damage 20
-   thrust speed 92
-   tier 9.86
-   weight 2.12
-   length 140
-   handling 77
Meowdao h1
- swing damage 44
- swing speed 81
- thrust damage 20
- thrust speed 92
- tier 9.94
- weight 2.06
- length 140
- handling 77
Meowdao h2
- swing damage 45
- swing speed 81
- thrust damage 21
- thrust speed 92
- tier 9.34
- weight 2.06
- length 140
- handling 77
Meowdao h3
- swing damage 46
- swing speed 82
- thrust damage 21
- thrust speed 92
- tier 9.90
- weight 2.01
- length 140
- handling 78
Zweihander h0
- swing damage 46
- swing speed 74
- thrust damage 21
- thrust speed 87
- tier 9.93
- weight 2.67
- length 160
- …

NewTwoHanded swords stats input

---

crafting_pieces.xml
items.json
items/weapons.xml

Elegant Shepherd's Axe v1.0 Stats
**Elegant Shepherd Axe - h0**
-    Weight: 1.2
-    Length: 105
-    Handling: 79
-    Swing Damage: 40 (Cut)
-    Swing Speed: 80
**Elegant Shepherd Axe - h1**
-    Weight: 1.2
-    Length: 105
-    Handling: 79
-    Swing Damage: 41 (Cut) **(+1)**
-    Swing Speed: 80
**Elegant Shepherd Axe - h2**
-    Weight: 1.2
-    Length: 105
-    Handling: 79
-    Swing Damage: 43 (Cut) **(+2)**
-    Swing Speed: 80
**Elegant Shepherd Axe - h3**
-    Weight: 1.19 **(-0.01)**
-    Length: 105
-    Handling: 79
-    Swing Damage: 44 (Cut) **(+2)**
-    Swing Speed: 81 **(+1)**

Elegant Shepherd's Axe v1.0

---

crafting_pieces.xml
items.json
items/weapons.xml

stats input for three new polearms: Pudao, FangTian ji, Norse Battle Axe (renamed from Meowaxe)
specific stats for each weapon:
Pudao h0
swing damage 40
swing speed 81
thrust damage 21
thrust speed 86
tier 9.92
weight 3.2
length 143
handling 76
Pudao h1
swing damage 40
swing speed 82
thrust damage 23
thrust speed 86
tier 9.76
weight 3.15
length 143
handling 77
Pudao h2
swing damage 42
swing speed 82
thrust damage 23
thrust speed 86
tier 9.97
weight 3.15
length 143
handling 77
Pudao h3
swing damage 42
swing speed 83
thrust damage 24
thrust speed 86
tier 9.87
weight 3.1
length 143
handling 78
FangTian Ji h0
swing damage 42
swing speed 77
thrust damage 23
thrust speed 89
tier 10
weight 2.53
length 169
handling 70
FangTian Ji h1
swing damage 43
swing speed 78
thrust damage 23
thrust speed 89 …

NewPolearms stats input

---

crafting_pieces.xml
items.json

Giving Norse Battle Axe BvS
Giving Norse Battle Axe thrust with blunt damage
Below are the stats:
Norse Battle Axe h0
swing damage 43
swing speed 82
thrust damage 20
thrust speed 89
tier 9.71
weight 2.64
length 110
handling 72
Norse Battle Axe h1
swing damage 44
swing speed 83
thrust damage 20
thrust speed 89
tier 9.78
weight 2.61
length 110
handling 72
Norse Battle Axe h2
swing damage 45
swing speed 83
thrust damage 22
thrust speed 89
tier 9.59
weight 2.58
length 110
handling 73
Norse Battle Axe h3
swing damage 47
swing speed 83
thrust damage 22
thrust speed 89
tier 9.77
weight 2.58
length 110
handling 73

rebalance Norse Battle Axe

---

crafting_pieces.xml
items.json
items/weapons.xml

stats input for two new 1h swords: Kopesh, Narrow Sword
specific stats for each weapon:
Kopesh h0
swing damage 33
swing speed 91
thrust damage 20
thrust speed 85
tier 10
weight 2.12
length 77
handling 88
Kopesh h1
swing damage 34
swing speed 91
thrust damage 22
thrust speed 85
tier 9.55
weight 2.12
length 77
handling 88
Kopesh h2
swing damage 35
swing speed 92
thrust damage 22
thrust speed 86
tier 9.96
weight 2.06
length 77
handling 88
Kopesh h3
swing damage 35
swing speed 93
thrust damage 24
thrust speed 87
tier 9.75
weight 2
length 77
handling 89
Narrow Sword h0
swing damage 33
swing speed 86
thrust damage 20
thrust speed 89
tier 9.57
weight 1.67
length 94
handling 89
Narrow Sword h1
swing damage 34
swing speed 87
thrust damage 20
thrust speed 90
tier 9.91
weight 1.62
length 94
handling …

NewOneHandedSwords Kopesh, Narrow Sword

---

items.json
items/body_armors.xml

Assigned crpg_rus_armour2
Name changed to Half Shiny, to fit the other 2 vaegir coat of plates

Assigned rus armor2

---

items.json
items/body_armors.xml

Assigned new coat of plate variants
Note, low armour coverage of the coat on back, therefore slightly lower body armour than first appears
Each named based on pattern
Renamed old brigandine with and w/o shoulder pads - Captial letter update

Assigned batch 4 coat of plates

---

crafting_pieces.xml
items.json
items/weapons.xml

Unable to confirm new model got in atm, will leave it here and ask for review for merge in after batch4
Rename Executioner's Sword to Ceremonial Executioner's Sword, rework is aiming at changing the purpose of this 2h sword from a sword with regular thrust ability and cut damage for swing into a similar position of Barmace. Therefore after the rework, thrust ability will be disabled, swing damage type will be changed to blunt. New stats at below:
Ceremonial Executioner's Sword h0
swing damage 29
swing speed 84
tier 9.39
weight 2.82
length 100
handling 82
Ceremonial Executioner's Sword h1
swing damage 29
swing speed 86
tier 9.78
weight 2.67
length 100
handling 83
Ceremonial Executioner's Sword h2
swing damage 30
swing speed 86
tier 9.51
weight 2.67
length 100
handling 83
Ceremonial …

ReworkExecutionersSword

---

crafting_pieces.xml
items.json
items/weapons.xml

Renamed Pudao to Podao (I misspelled). Stats rework for: Burgundian Poleaxe, FangTian Ji, Podao. Rework aims to increase the useability of those weapons, also giving the Polearm category more different choices at different reach/style. Will closely monitor and will be prepared for any further small adjustments.
Newest stats are provided below (weapons refunded):
Burgundian Poleaxe h0
swing damage 41 to 44
swing speed 80 to 78
thrust damage 25 to 24
thrust speed 91 to 89
new tier 9.44
weight 2.36 to 2.44
handling 71 to 70
Burgundian Poleaxe h1
swing damage 42 to 45
swing speed 81 to 79
thrust damage 25 to 24
thrust speed 91 to 89
new tier 9.47
weight 2.31 to 2.41
handling 72 to 70
Burgundian Poleaxe h2
swing damage 43 to 45
swing speed 81 to 80
thrust damage 27 to 26
thrust speed 91 to 89 …

10.24 Polearm Adjustments

---

crafting_pieces.xml
crafting_templates.xml
items.json
items/weapons.xml
weapon_descriptions.xml

- Moved Steel Round Axe to mace group to enable thrust
- Added BvS tag to Steel Round & Knightly Spiked in mace group
- Lowered thrust dmg on Knightly Spiked Axe to get within budget

1h axe.update.oct2023

---

crafting_pieces.xml
crafting_templates.xml
items.json
items/shields.xml
items/weapons.xml

Changes the Green & Red Nodachi - Cuts off lower level damage but increases speed marginally due to weapon being too slow for what it is. Overall slight tier increase.
Changes x2 Pavise shields:
1) Reinforced Pavise - Turned this into the high health strong powerhouse shield that weighs a lot - Designed to be used by battlefield tanks who want to sacrifice movespeed for a powerful shield
2) Pavise - Turned this into a lighter but high armour variant of the shield, designed to be used by those who seek an anti-ranged strategy with lots of coverage but weaker in melee combat in contrast.
Refund issued for Pavise shields as they would be fundamentally changed
No refund issued for Nodachi as the tweak is slight and only serves to better the weapon overall.

Nodachi & Pavise changes v1.0

---

items/weapons.xml

Arrow Rework v1
- Created 3 different HA Arrow-Types, lighter arrows for Horsearchers
- 0.035 weight per Arrow
- "Elite Steppe Arrows", 30 Arrows, 3p
- "Stacked Steppe Arrows", 35 Arrows, 2p
- "Simple Steppe Arrows" (old Lowland Arrows), 40 Arrows, 1p
- Lowland Arrows became Simple Steppe Arrows, changed it's quiver from back to waist
- "Barbed Arrows" are now Cut Arrows, 40 Arrows, 6c
- renamed "Arrows" to "Simple Arrows", they now deal 1p
- "Range Arrows" now deal 2p
Weight-Rework: (Arrows got their weight adjusted, similar to the tiering system already applied to bows)
- all HA Arrows: 0.035
- Best to worst Cut-Arrows: 
- 0.045, 0.040, 0.035 weight
- Best to worst Pierce and Blunt-Arrows: 
- 0.1, 0.095, 0.09, 0.085

Arrow-Rework

---

items.json
items/weapons.xml

Reworked Hunting Bows:
- Applied Long_Bow usage set. (To prevent horsearchers using them)
- Buffed them slightly to fill up some of the now missing tier due to not being able to be used on Horse anymore
- Refunded them

Hunting Bow Rework

---

crafting_pieces.xml
items/weapons.xml

Throwing.Update.NOV2023 (if accepted)
Mostly a pass on weight of some throwing items to make lighter versions for skirmishers
Lowland Javelin = Skirmsher Javelin:  -weight, +dmg
Woodland = Steel Skirmisher Javelin: -weight
Jagged Spear = Skirmsher Throwing Spear: -weight, -dmg
---------------------------------------------------------
Fish Harpoon: -weight, +2dmg
Simple Javelin: -weight
Throwing Star Diamond: +2 dmg
Throwing Star Triangle: consistent weight and stack amount
Pilum: switched back to single stack version to avoid unintended ammo bugs picking up other javelins

Throwing.update.nov2023

---

crafting_pieces.xml
items/shields.xml
items/weapons.xml

RomanEquip.Update.NOV2023 (if accepted)
-Strengthened 2 Oval shields to give Roman's better selection
-Renamed and updated 4 Spatha's with better thrusting specs
-Spatha to Cavalry Spatha, reach + high cut, slow
-Spatha with Narrow Fuller to Imperial Spatha, slightly more cut than thrust
-Iron Spatha to Republican Spatha, equal cut and thrust
-Spatha Blade with Ring Pommel to Prefect's Spatha, thrust specialty
-Updated 1 Sturgian shortsword to be thrust speciality (Gauls!)

Roman equip.update.nov2023

---

items/body_armors.xml
items/head_armors.xml
items/leg_armors.xml
items/shoulder_armors.xml

This was done since TW changed many materials to allow for team color, our items are now synced by mesh name to have the flag set true if the native items has it set to true.

Synced the UseTeamColor flag setting for all native items

---

crafting_pieces.xml
items/weapons.xml

Updated the 4x 1h Maces above 93 speed to slow them down and compensated by reducing weight, increasing damage and/or reach.
•	Blacksmith Hammer: -4 spd, +9 length, +1 dmg, -0.26 w, updated heirloom model for all +dmg
•	Decorated Round Mace: -2 spd, +2 dmg, -0.53 w, updated heirloom model for all +dmg
•	Short Western Mace: -4 spd, +2 dmg, -0.08 w
•	Light Winged Mace: renamed to ‘Winged Mace’, -8 spd, +0.46 w, +3 dmg (changed tiers as many similar of that length/speed/dmg)
•	All changed weapons refunded

1h mace.update.dec2023

---

crafting_pieces.xml
items/weapons.xml

Increase of Polehammer to T9.8 to give a better spread of blunt/pierce polearms. New spread:
T2 - Bo Staff
T5 - Bludgeon Staff
T7.5 - Iron Rod (pending Yeldur change, from T5)
T8.5 - Bec de Corbin
T10 - Polehammer (pending this change, from T7.5)

Increase Polehammer to T9.8

---

crafting_pieces.xml
items/weapons.xml

Long Thamaskene Tipped Spear adjusted to be a more swing-focused spear that encourages putting away shield to fight with to maximise the quite nice swing damage. Created following the General Longform on the Discord, providing a long and damaging polearm that should feel good to fight with.
Thamaskene chosen because the current swing values are largely a waste of budget and other 4D spears occupy the same "space".
New and improved by not going over T10!

Thamaskene swing pole

---

crafting_pieces.xml
items/weapons.xml

was too close to the short western mace (only stat difference was 2 length and 1 handling).
so dropped damage to 20b and increased speed to 94, hopefully not too much speed (max 94 currently). 
contrasts with short western mace and blacksmith hammer generally.
at least now it is a bit more of a different option to pick between them.
any feedback welcome

Mace adjust Decorated Round Mace 

---

crafting_pieces.xml
weapon_descriptions.xml

swing polearm length and damage is now more impactful on its tier
probably needs a refund once crafting work has been done to bring tiers in line with budget changes

polearm swing nerf

---

crafting_pieces.xml
items/weapons.xml

Rework Heavy Blacksmith Hammer to increase variety
It was noted that a lot of maces in 2h form have less, or similar damage to that of 1h, the reasoning for this is because almost all 2h maces have a flag attached that reduces their budget. This change serves to resolve that issue by reworking an underwhelming 2h mace that is seldom used and giving it stats without flags.

Heavy Blacksmith Hammer rework

---

crafting_pieces.xml
items/weapons.xml

Rework daggers to increase high tier cut options
Reworks Tanto, Seax and Ancient Long Dagger to increase higher tier dagger options in the form of Cut as they were originally built to be weaker than Stab-Only as they were intended to be able to block. As they can no longer block, a rework to increase stats makes sense.
Lowers the tier of Decorative Dagger as the stats given to it as a bonus for looms were too high for what the weapon is intended to be.
Tanto, Seax, ALD and DD are refunded as part of this rework.

Yeldur Dagger Rework

---

items/weapons.xml

fully refund xbows/bolts
due to a mistake made during the last patch resulting in incorrect STR reqs for xbows being listed on the website, a full refund of xbows/bolts feels necessary to ensure people are able to make an informed choice based on the changes made to xbow.

xbow refund

---

items/head_armors.xml

Fix incorrect prices set against staff helmets
Helmets had 'value' set manually in helmets.xml which overwrote the items.json making them incredibly expensive, this was missed in PR review.
Addressed issue of PR review by making it a mandatory step to review xml for a manual `value` set against it.
Addressing issues here by fixing prices now.

Fix incorrect prices set against staff helmets

---

items/weapons.xml

Refunds the following items, based on not happening for https://github.com/namidaka/itembalancing/pull/528
- All melee weapons which have blunt damage
- Cut & pierce damage maces
Note includes slight "changes" to Tier based on a "change" Nami did for Tier calc. Nothing has actually changed, tiers and costs have very very slightly adjusted for most weapons - think 6th decimal place for tier. It was part of putting in the code to allow for tier stretching. @namidaka just tagging you for more info if required.

Refund blunt from v114 changes

---

crafting_pieces.xml

redistribute partisan weights in line with fine steel leaf spear, see math table in.  Lowers handling by 1, and reduces balance metric.  Also updates the ornate pauldrons items.json back to correct weight and tier stats.

redistribute partisan weights in line with fine steel leaf spear

---

crafting_pieces.xml
items/weapons.xml

Rework Bill & Billhook, reorganise Billhook components in `crafting_pieces.xml`, to ensure they are grouped together.
Currently we don't have (m)**any**(?) 4D dismount weapons, this change serves to add this into the mix by reworking two weapons that are currently seldom used in the hopes of granting them more space on the field in the form of buffing a niche they can fill.
This PR also reorganises the Billhook components within `crafting_pieces.xml`, ensuring they are grouped together. This adjustment does not alter the item's functionality, but rather serves to improve QoL by preventing pieces being scattered randomly throughout the XML.

Bill & Billhook Rework

---

crafting_pieces.xml
items/weapons.xml

Attempted through budget change, but it was a headache that every single weapon gets changed when really it's just a handful - those at top tier who spend a lot of budget on speed.
Weapons have been slowed down, some stats given back in damage and/or reach (refunded):
- Katanas (all)
- Longsword
- Langes Messer
- Ancient Fighting Axe
- Decorated Great Saber
- Northlander Wide Fullered Greatsword

Slowed down "problem" fast weapons

---

crafting_pieces.xml

Fix CanHook & CanDismount weapons by applying both flags to all items
Currently CanHook does not display on the website and applies to swings
CanDismount does display on the website and applies to stabs
This leads to confusion in that, people expect a weapon to be able to Dismount when CanDismount displays on the site when it only does this with stabs.
This change addresses these issues by adding CanHook to any weapon with CanDismount & vice versa. (Exception for Partisan as it was intended to only have one, and this will be addressed by another method)

Fix CanDismount and CanHook flags

---

crafting_pieces.xml
items/weapons.xml

Updated stats and loom paths for various Roman-style weapons, for more "useable" 1h cut options with ACIV coming
Mainz Gladius
Republican Gladius
Pompeiian Gladius
Cavalry Spatha
Imperial Spatha
Prefects Spatha
Refunds issued

Roman weapons rebalance

---

crafting_pieces.xml
items/horses_and_others.xml
items/weapons.xml
weapon_descriptions.xml

- Spiked Polehammer main mode corrected to non-knockdown version
- Corrected Western Heavy Harness family type (needs re-enabling after patch)
- Corrected Ibelin Sword heirloom naming
- Removed Hoplite Spear ability to dismount
- Removed the no damage stab animation from "Bill"
- Enabled Handgonne + Black powder ammo (triggers refund)
- Slightly tiered down the Cataphract Lance so upkeep isn't too high

Fixes and tweaks from v116

---

crafting_pieces.xml
items/weapons.xml

Rebalance Hoplite Spear for fairer balancing
Hoplite Spear for a while now has been a consistent outlier in how strong it is, as a result this change is to address this issue.
From review, I believe the Spear is a victim of rushed and/or lazy crafting resulting in most of the components weight being empty and all the weight being dumped into a single component (something we now know to cause issues in weapons) 
This change re-balances the weapon and elongates it slightly to take away some of its stat strength as a result of its short current length as well as remove its ability to dismount.

Rebalance Hoplite Spear

---

crafting_pieces.xml

The Bill and now Nagamaki caused a crash which was solved by giving them their thrust back. Other twohandedpolearms that have no thrust also have no shield usage - this has been added to Bill ana Nagamaki so should no longer cause a crash

Fixed twohanded polearm no thrust itemusage

---

items/head_armors.xml

This adds two morion variants that are black etched instead of gilded, stats are identical.

Added black etched Morion variants

---

items/weapons.xml

This adds two disable versions of the guns as test objects. This adds two stage reload to guns by asigning them the light xbow reload item usage.  They already use light xbow animation and not stuck in place, intent of this is to split that into two stages.  Guns are balanced back to same tier as previously **only** by reducing reload speed.  We can test to see how much this changes effective reload speed. Also curious to see how this effects starting, whether it starts loaded or not.

test two stage reload light xbow method

---

crafting_pieces.xml
items/weapons.xml

Meowdao presently suffers with an issue of bad weight distribution leading to exceptionally slow swings, this change serves to better redistribute weight between components.
Currently this does lower the tier of the weapon as it loses handling, at present I've chosen to ignore this as I think it may be better off filling a space in the slightly-lower tiers for a more budget-friendly 2h (which are sorely lacking in the 2h category rn) - This can however be adjusted if we feel it necessary.

Fix Meowdao weight distrib issue

---

items/body_armors.xml

Adjusted outlier armors in accordance with balance team direciton to normalize (body/arm+leg) armor ratios.  Intent was to keep tier the same, redistributing body armor to arms and legs as made visual sense.  Lorica musculata had slight increase in tier as it did not seem visually consistent to lower the body armor on that piece.  Ratio goal is <~2.6

adjust outlier armors for body to arm leg ratio
